export const SIGNUP_REQUEST = 'auth/SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'auth/SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'auth/LOGOUT_FAILURE';

export const RECEIVE_AUTH_REQUEST = 'auth/RECEIVE_AUTH_REQUEST';
export const RECEIVE_AUTH_SUCCESS = 'auth/RECEIVE_AUTH_SUCCESS';
export const RECEIVE_AUTH_FAILURE = 'auth/RECEIVE_AUTH_FAILURE';