export const FETCH_MY_CHATS_REQUEST = 'chats/FETCH_MY_CHATS_REQUEST';
export const FETCH_MY_CHATS_SUCCESS = 'chats/FETCH_MY_CHATS_SUCCESS';
export const FETCH_MY_CHATS_FAILURE = 'chats/FETCH_MY_CHATS_FAILURE';

export const FETCH_ALL_CHATS_REQUEST = 'chats/FETCH_ALL_CHATS_REQUEST';
export const FETCH_ALL_CHATS_SUCCESS = 'chats/FETCH_ALL_CHATS_SUCCESS';
export const FETCH_ALL_CHATS_FAILURE = 'chats/FETCH_ALL_CHATS_FAILURE';

export const FETCH_CHAT_REQUEST = 'chats/FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCESS = 'chats/FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILURE = 'chats/FETCH_CHAT_FAILURE';

export const CREATE_CHAT_REQUEST = 'chats/CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'chats/CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAILURE = 'chats/CREATE_CHAT_FAILURE';

export const JOIN_CHAT_REQUEST = 'chats/JOIN_CHAT_REQUEST';
export const JOIN_CHAT_SUCCESS = 'chats/JOIN_CHAT_SUCCESS';
export const JOIN_CHAT_FAILURE = 'chats/JOIN_CHAT_FAILURE';

export const LEAVE_CHAT_REQUEST = 'chats/LEAVE_CHAT_REQUEST';
export const LEAVE_CHAT_SUCCESS = 'chats/LEAVE_CHAT_SUCCESS';
export const LEAVE_CHAT_FAILURE = 'chats/LEAVE_CHAT_FAILURE';

export const DELETE_CHAT_REQUEST = 'chats/DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'chats/DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'chats/DELETE_CHAT_FAILURE';

export const SEND_MESSAGE_REQUEST = 'chats/SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'chats/SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'chats/SEND_MESSAGE_FAILURE';

export const SET_ACTIVE_CHAT = 'chats/SET_ACTIVE_CHAT';
export const UNSET_ACTIVE_CHAT = 'chats/UNSET_ACTIVE_CHAT';