export const SOCKET_CONNECTION_REQUEST = 'sockets/SOCKET_CONNECTION_REQUEST';
export const SOCKET_CONNECTION_SUCCESS = 'sockets/SOCKET_CONNECTION_SUCCESS';
export const SOCKET_CONNECTION_FAILURE = 'sockets/SOCKET_CONNECTION_FAILURE';
export const SOCKET_CONNECTION_MISSING = 'sockets/SOCKET_CONNECTION_MISSING';

export const MOUNT_CHAT = 'sockets/MOUNT_CHAT';
export const UNMOUNT_CHAT = 'sockets/UNMOUNT_CHAT';

export const SEND_MESSAGE = 'sockets/SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'sockets/RECEIVE_MESSAGE';
export const RECEIVE_NEW_CHAT = 'sockets/RECEIVE_NEW_CHAT';
export const RECEIVE_DELETED_CHAT = 'sockets/RECEIVE_DELETED_CHAT';